import '../../shared/models/exercise.dart';

class ExerciseSeed {
  static List<Exercise> getExercises() {
    return [
      // ANAERÓBICOS - PEITO
      Exercise(
        id: 'supino_reto',
        name: 'Supino Reto',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.chest,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Exercício clássico para desenvolvimento do peitoral',
      ),
      Exercise(
        id: 'supino_inclinado',
        name: 'Supino Inclinado',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.chest,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Supino com inclinação de 30-45 graus',
      ),
      Exercise(
        id: 'supino_declinado',
        name: 'Supino Declinado',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.chest,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Supino com declinação de 15-30 graus',
      ),
      Exercise(
        id: 'crucifixo',
        name: 'Crucifixo',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.chest,
        equipment: 'Halteres',
        defaultUnit: ExerciseUnit.kg,
        description: 'Movimento de abertura dos braços com halteres',
      ),
      Exercise(
        id: 'flexao_braco',
        name: 'Flexão de Braço',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.chest,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.reps,
        description: 'Exercício de peso corporal para peitoral',
      ),

      // ANAERÓBICOS - COSTAS
      Exercise(
        id: 'remada_curvada',
        name: 'Remada Curvada',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.back,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Puxada da barra em direção ao abdômen',
      ),
      Exercise(
        id: 'puxada_barra',
        name: 'Puxada na Barra',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.back,
        equipment: 'Barra fixa',
        defaultUnit: ExerciseUnit.reps,
        description: 'Puxada do corpo em direção à barra',
      ),
      Exercise(
        id: 'pulldown',
        name: 'Pulldown',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.back,
        equipment: 'Cabo',
        defaultUnit: ExerciseUnit.kg,
        description: 'Puxada do cabo para as costas',
      ),
      Exercise(
        id: 'remada_unilateral',
        name: 'Remada Unilateral',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.back,
        equipment: 'Halter',
        defaultUnit: ExerciseUnit.kg,
        description: 'Remada com um braço por vez',
      ),

      // ANAERÓBICOS - OMBROS
      Exercise(
        id: 'desenvolvimento_militar',
        name: 'Desenvolvimento Militar',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.shoulders,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Elevação da barra acima da cabeça',
      ),
      Exercise(
        id: 'elevacao_lateral',
        name: 'Elevação Lateral',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.shoulders,
        equipment: 'Halteres',
        defaultUnit: ExerciseUnit.kg,
        description: 'Elevação lateral dos braços',
      ),
      Exercise(
        id: 'elevacao_frontal',
        name: 'Elevação Frontal',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.shoulders,
        equipment: 'Halteres',
        defaultUnit: ExerciseUnit.kg,
        description: 'Elevação frontal dos braços',
      ),

      // ANAERÓBICOS - BRAÇOS
      Exercise(
        id: 'rosca_direta',
        name: 'Rosca Direta',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.arms,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Flexão dos antebraços com barra',
      ),
      Exercise(
        id: 'rosca_martelo',
        name: 'Rosca Martelo',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.arms,
        equipment: 'Halteres',
        defaultUnit: ExerciseUnit.kg,
        description: 'Rosca com pegada neutra',
      ),
      Exercise(
        id: 'triceps_testa',
        name: 'Tríceps Testa',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.arms,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Extensão dos braços com barra',
      ),
      Exercise(
        id: 'triceps_pulley',
        name: 'Tríceps Pulley',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.arms,
        equipment: 'Cabo',
        defaultUnit: ExerciseUnit.kg,
        description: 'Extensão dos braços no cabo',
      ),

      // ANAERÓBICOS - PERNAS
      Exercise(
        id: 'agachamento_livre',
        name: 'Agachamento Livre',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.legs,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Agachamento com barra nas costas',
      ),
      Exercise(
        id: 'leg_press',
        name: 'Leg Press',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.legs,
        equipment: 'Máquina',
        defaultUnit: ExerciseUnit.kg,
        description: 'Pressão das pernas na máquina',
      ),
      Exercise(
        id: 'levantamento_terra',
        name: 'Levantamento Terra',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.fullBody,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Levantamento da barra do chão',
      ),
      Exercise(
        id: 'stiff',
        name: 'Stiff',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.legs,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Flexão do quadril com barra',
      ),
      Exercise(
        id: 'panturrilha_pe',
        name: 'Panturrilha em Pé',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.calves,
        equipment: 'Máquina',
        defaultUnit: ExerciseUnit.kg,
        description: 'Elevação dos calcanhares',
      ),
      Exercise(
        id: 'elevacao_quadril',
        name: 'Elevação de Quadril',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.glutes,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.reps,
        description: 'Elevação do quadril deitado',
      ),

      // AERÓBICOS
      Exercise(
        id: 'corrida_esteira',
        name: 'Corrida (Esteira)',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Esteira',
        defaultUnit: ExerciseUnit.time,
        description: 'Corrida na esteira',
      ),
      Exercise(
        id: 'corrida_externa',
        name: 'Corrida Externa',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Nenhum',
        defaultUnit: ExerciseUnit.time,
        description: 'Corrida ao ar livre',
      ),
      Exercise(
        id: 'bicicleta_ergometrica',
        name: 'Bicicleta Ergométrica',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Bicicleta',
        defaultUnit: ExerciseUnit.time,
        description: 'Pedalada na bicicleta ergométrica',
      ),
      Exercise(
        id: 'spinning',
        name: 'Spinning',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Bicicleta',
        defaultUnit: ExerciseUnit.time,
        description: 'Aula de spinning',
      ),
      Exercise(
        id: 'eliptico',
        name: 'Elíptico',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Elíptico',
        defaultUnit: ExerciseUnit.time,
        description: 'Exercício no elíptico',
      ),
      Exercise(
        id: 'caminhada',
        name: 'Caminhada',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Nenhum',
        defaultUnit: ExerciseUnit.time,
        description: 'Caminhada',
      ),
      Exercise(
        id: 'pular_corda',
        name: 'Pular Corda',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Corda',
        defaultUnit: ExerciseUnit.time,
        description: 'Pular corda',
      ),
      Exercise(
        id: 'remo_ergometro',
        name: 'Remo (Ergômetro)',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.fullBody,
        equipment: 'Remo',
        defaultUnit: ExerciseUnit.time,
        description: 'Remo no ergômetro',
      ),
      Exercise(
        id: 'hiit',
        name: 'HIIT (Circuito)',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.fullBody,
        equipment: 'Nenhum',
        defaultUnit: ExerciseUnit.time,
        description: 'Treino intervalado de alta intensidade',
      ),
      Exercise(
        id: 'escada_step',
        name: 'Escada/Step',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.legs,
        equipment: 'Escada',
        defaultUnit: ExerciseUnit.time,
        description: 'Subida de escadas ou step',
      ),

      // EXERCÍCIOS ADICIONAIS
      Exercise(
        id: 'abdominal_crunches',
        name: 'Abdominal Crunches',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.core,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.reps,
        description: 'Abdominal tradicional',
      ),
      Exercise(
        id: 'prancha',
        name: 'Prancha',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.core,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.time,
        description: 'Isometria na posição de prancha',
      ),
      Exercise(
        id: 'mountain_climbers',
        name: 'Mountain Climbers',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.fullBody,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.time,
        description: 'Exercício de alta intensidade',
      ),
      Exercise(
        id: 'burpees',
        name: 'Burpees',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.fullBody,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.time,
        description: 'Exercício completo de alta intensidade',
      ),
      Exercise(
        id: 'polichinelo',
        name: 'Polichinelo',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.cardio,
        equipment: 'Nenhum',
        defaultUnit: ExerciseUnit.time,
        description: 'Exercício cardiovascular básico',
      ),
      Exercise(
        id: 'afundo',
        name: 'Afundo',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.legs,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.reps,
        description: 'Exercício unilateral para pernas',
      ),
      Exercise(
        id: 'agachamento_salto',
        name: 'Agachamento com Salto',
        category: ExerciseCategory.aerobic,
        muscleGroup: MuscleGroup.legs,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.time,
        description: 'Agachamento com explosão',
      ),
      Exercise(
        id: 'flexao_diamante',
        name: 'Flexão Diamante',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.arms,
        equipment: 'Peso corporal',
        defaultUnit: ExerciseUnit.reps,
        description: 'Flexão com mãos próximas',
      ),
      Exercise(
        id: 'puxada_pegada_aberta',
        name: 'Puxada Pegada Aberta',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.back,
        equipment: 'Barra',
        defaultUnit: ExerciseUnit.kg,
        description: 'Puxada com pegada mais aberta',
      ),
      Exercise(
        id: 'desenvolvimento_halteres',
        name: 'Desenvolvimento com Halteres',
        category: ExerciseCategory.anaerobic,
        muscleGroup: MuscleGroup.shoulders,
        equipment: 'Halteres',
        defaultUnit: ExerciseUnit.kg,
        description: 'Desenvolvimento com halteres',
      ),
    ];
  }
}
